
package l4q1;

//two player means two users, but using random generated by computer

import java.util.Random;



public class L4Q5 {  //DONEEE ALHAMDULILLAH!!!
    
    public static void main(String[] args){
        Random r=new Random();
        int p1,p2,a,b,sum1=0,sum2=0;
        final int SIZE=6;
        System.out.println("DICE GAME\n"); 
        
        for(int i=1;i<Integer.MAX_VALUE;i++){
            
        //PLAYER 1          
        p1=r.nextInt(SIZE)+1;
        System.out.println("player 1: "+p1);
        sum1+=p1;   
        System.out.println("total player 1: "+sum1);
        if(p1==6){
            a=r.nextInt(SIZE)+1;
            System.out.println("player 1: "+a);
            sum1+=a;
            System.out.println("total player 1: "+sum1);
        }    
            
        if(sum1==100){
            System.out.println("player 1 wins!");
            break;
        }
            System.out.println();
        //PLAYER 2       
        p2=r.nextInt(SIZE)+1;
        System.out.println("player 2: "+p2);
        sum2+=p2;
        System.out.println("total player 2:"+sum2);
        if(p2==6){
            b=r.nextInt(SIZE)+1;
            System.out.println("player 2: "+b);
            sum2+=b;
            System.out.println("total player 2:"+sum2);
        }     
            
       if(sum2==100){      
           System.out.println("player 2 wins!");
           break;
       }
            System.out.println();
        }
       
        
        
    }
    
}
